tsParticles.load("particles",{
particles:{
number:{value:100},
color:{value:["#8b5cf6","#3b82f6"]},
shape:{type:"circle"},
opacity:{value:{min:0.2,max:0.6}},
size:{value:{min:1,max:3}},
move:{
enable:true,
speed:0.4,
random:true,
outModes:"out"
},
links:{enable:false}
},
interactivity:{
events:{onHover:{enable:true,mode:"bubble"}},
modes:{bubble:{distance:130,size:5}}
}
});